### PR TITLE
Add anime girl read Java book

### PR DESCRIPTION
**Pull request by rusIand**

### CODE REVIEW

**Comment by SoftwareGuy** [comment]
I think you need to rename these files to reflect what the recommended filename structure. 

That last one, "Read_Anime.png" is clearly Patchouli Knowledge from the Touhou series. It wouldn't be hard for you to even run SauceNao to have it identify the artworks.

Make it less painful for the pull request reviewers.

**Comment by marginaI** [comment]
Sorry, but out of 6 photos, I found the original source with only 1

**Review by cat-milk — CHANGES_REQUESTED** [review]
I like these but if possible could you try to add character names to some more of these.

If you don't know the names you can just use `Unknown_${bookDetails}` and if you know for a fact that the character is simply unnamed (like in the case of some artist ocs) you can just use `Unnamed_${bookDetails}`.

**Review by gabrieldasilvadev — APPROVED** [review]

**Comment by cat-milk** [comment]
@fI0ki I'm bumping this in case you're still interested in getting this merged. This PR has been open for a year and a half so I'm going to assume you aren't keeping track of it anymore if I don't hear back by the time I check on this repo again (probably like a month or two from now given my track record lol)

**Pull request closed without merging**
