### PR TITLE
Add Mikuru Asahina holding Introduction to Reversible Computing

### PR DESCRIPTION
**Pull request by shannaurelle**

### CODE REVIEW

**Review by trackpadpro — CHANGES_REQUESTED** [review]
This really doesn't align with the hands

**Comment by Delnold** [comment]
> This really doesn't align with the hands

With much respect to you guys, how did you manage to ignore 2 legit PR's before this one. They are already 9,18 days old.

**Comment by trackpadpro** [comment]
> With much respect to you guys, how did you manage to ignore 2 legit PR's before this one. They are already 9,18 days old.

To be clear, I am not a maintainer and do not have the ability to actually approve anything. I am just making an improvement suggestion because this PR is significantly lower quality than the others. Also, before you go complaining about a PR backlog, feel free to actually look at the backlog and realize that I myself have an open one from a month ago

**Comment by Delnold** [comment]
> > With much respect to you guys, how did you manage to ignore 2 legit PR's before this one. They are already 9,18 days old.
> 
> To be clear, I am not a maintainer and do not have the ability to actually approve anything. I am just making an improvement suggestion because this PR is significantly lower quality than the others. Also, before you go complaining about a PR backlog, feel free to actually look at the backlog and realize that I myself have an open one from a month ago

Sorry man, this is actually hilarious. Theory about your PR: I guess they are making approval only once, and never check them again. As others PR's were actually approved.

**Comment by Delnold** [comment]
> To be clear, I am not a maintainer and do not have the ability to actually approve anything. I am just making an improvement suggestion because this PR is significantly lower quality than the others. Also, before you go complaining about a PR backlog, feel free to actually look at the backlog and realize that I myself have an open one from a month ago

Sorry man, this is actually hilarious. Theory about your PR: I guess they are making approval only once, and never check them again. As others PR's were actually approved.

**Pull request closed without merging**
