### PR TITLE
add makise kurisu holding K&R book

### PR DESCRIPTION
**Pull request by hypervis0r**
kurisu is the only thing giving me hope to go on as a systems programmer

### CODE REVIEW

**Comment by Caslus** [comment]
i think the book cover could be improved a bit so it doesn't overlap the pages on top

**Comment by hypervis0r** [comment]
> i think the book cover could be improved a bit so it doesn't overlap the pages on top

does it really matter

**Comment by kuator** [comment]
> i think the book cover could be improved a bit so it doesn't overlap the pages on top

Sorry for chiming in, but I think I agree, it would improve the image if we matched the cover to the book
kirisu

**Review by AntonCkya — CHANGES_REQUESTED** [review]
meh, bad cutted

**Comment by cat-milk** [comment]
This has been inactive for 2 years and a similar image already got added since then by another PR so I'm closing this

**Pull request closed without merging**
