### PR TITLE
Lossless image compression

### PR DESCRIPTION
**Pull request by RDKRACZ**
Images were optimized using the [Leanify](https://github.com/JayXon/Leanify) tool.

### CODE REVIEW

**Comment by asheeeshh** [comment]
we can also add [ImgBot](https://github.com/marketplace/imgbot) for future prs, it optimizes the files automatically.

**Comment by kotx** [comment]
We can also just turn everything into WebPs :P

**Comment by Asday** [comment]
Yeah so they don't open in any program except a bunch of botnet ones, no thanks.

@RDKRACZ what was the information that was removed from these?  The diffs are not useful because these are binary files, and there's every reason to believe the original authors might have stuff they intended to be in there.  Added to that - nobody that matters has so far cared about the space these images take up once we figured out that the size limits on github repos weren't going to cause us a problem.

**Comment by kotx** [comment]
>Yeah so they don't open in any program except a bunch of botnet ones, no thanks.

??? https://caniuse.com/?search=webp - every modern browser supports them, even on phones
Microsoft has https://www.microsoft.com/en-us/p/webp-image-extensions/9pg2dk419drg too if that doesn't work
https://www.irfanview.com/
https://www.getpaint.net/
Even ffplay opens them
GitHub embeds them
Discord embeds them

**Comment by Asday** [comment]
Browsers = botnets.
Phones = botnets.
Discord = come on now

The list of image viewers which can open webp is orders of magnitude shorter than the list of those that can.  The list of image viewers that can't open PNGs or JPGs is practically non-existent.

**Comment by Asday** [comment]
> we actually need to think about it

The venerable @cat-milk has not once rejected a PR because a file was not optimised.

> there is a lot of difference in the time it takes for a 5mb file to load and a 200kb file to load

Which file did you losslessly convert from 5M to 200K?

> do you expect them to download gigabytes of data for that?

Yes?

**Comment by cat-milk** [comment]
> We can also just turn everything into WebPs :P

no they are the most obnoxious image format. half the things you try to open or send them to people with just dont work. i will die on this hill

**Comment by cat-milk** [comment]
tbh cutting down filesize would be great but I dont want merge something i dont understand. Image encoding is dark magic to me

**Pull request closed without merging**
