### PR TITLE
Added a ReCT one

### PR DESCRIPTION
**Pull request by Khhs167**
ReCT do be fairly unknown as a language, but we've still got the image :)

### CODE REVIEW

**Comment by cat-milk** [comment]
Id like to get the girls name before merging this

**Comment by lingegrino** [comment]
Renge Miyouchi from Non non biyori

**Comment by bucket3432** [comment]
Please make sure to get the name right. It's spelled `Miyauchi` with an `a`, and `Renge` is the given name.

**Review by Caslus — CHANGES_REQUESTED** [review]
should be good once file is renamed to renge miyauchi holds rect book or something like that

**Comment by RDKRACZ** [comment]
The girl was renamed so the label can be now removed.
https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/commit/f8d3bac82ab0da2447c9557da360aab22d5f465f.

**Pull request merged**
