### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MayankVikash**
Minor Grammar Changes, will do more later

### CODE REVIEW

**Comment by flyingcakes85** [comment]
This PR reminds me of 2020 Hacktoberfest.

**Comment by Asday** [comment]
:-1: that is not the title of the repo which is the whole point.

Also neither "grammar" nor "changes" are proper nouns and thus don't require capitalisation.

> This PR reminds me of 2020 Hacktoberfest.

I was thinking practically the same thing.  Gotta get them t-shirts.

**Comment by cat-milk** [comment]
i like it the way it is

**Comment by MayankVikash** [comment]
> i like it the way it is

No Problem bro. By the way Thanks for the images!

**Pull request closed without merging**
