### PR TITLE
Add Abiko Samejima with The C Programming Language

### PR DESCRIPTION
**Pull request by DanArmor**

### CODE REVIEW

**Comment by BenBE** [comment]
The perspective of this looks wrong. If you hold a book like this, what you would see is part of the text on the page of the book with text flowing left to right. The cover page would only be partially visible on the right side (behind what is folded over).

**Comment by DanArmor** [comment]
You're right. Is it better now?

**Comment by BenBE** [comment]
Looks much better now. There's still some nitpicking you could do regarding the curvature of the front page, but that's much less noticeable unless you look for such details.

**Comment by cat-milk** [comment]
good job on this edit

**Pull request merged**
