### PR TITLE
Remove commits containing NSFW image

### PR DESCRIPTION
**Pull request by cat-milk**
Based on cat-milk/Anime-Girls-Holding-Programming-Books#517

I realized that couple of the commits in the original PR add and then delete an image that probably gets a little too close to being NSFW than I'd like. This PR just to removes the offending commits that original PR introduced to them out of the history on main

### CODE REVIEW

**Comment by cat-milk** [comment]
Bleh it looks like github's revert feature doesn't actually end up removing those commits from the history like I expected it to. I'm marking this PR as a draft till I can fix the history to remove those commits completely.

**Comment by Asday** [comment]
`revert` is a git feature, not a github one, and all it does is do the exact opposite of what the commits it's reverting did.  The idea is to preserve history.

You're looking for `rebase`, which will modify history (which has a nice big chance of losing data, there's a reason people don't like it), and force pushing.

**Comment by kotx** [comment]
> You're looking for `rebase`, which will modify history (which has a nice big chance of losing data, there's a reason people don't like it), and force pushing.

Wouldn't that break existing copies of the repo?

**Comment by cat-milk** [comment]
> Wouldn't that break existing copies of the repo?

It would but only for forks of the repo that happened after when the offending commit happened. I don't think there are too many forks like that yet so I don't think its a big deal

**Comment by cat-milk** [comment]
I ended up not completely reverting the original PR and only got rid of a couple of its commits instead since the image it was intending to add to the repo is actually fine

**Comment by cat-milk** [comment]
Bleh merging didn't work how I expected it to either, I'm leaving this marked as merged even though I actually just force pushed revert-517-kaori to master

**Pull request merged**
