### PR TITLE
Add a few girls holding various books and move one picture

### PR DESCRIPTION
**Pull request by ChristophGra**

### CODE REVIEW

**Comment by Kholodets** [comment]
where'd akko go? gh is saying the file was just deleted

**Comment by ChristophGra** [comment]
Ok, looked into it, I forgot to add the file back in.

Should've used git mv instead of doing it in the file explorer.

**Comment by Kholodets** [comment]
:+1:

**Comment by Kholodets** [comment]
i usually just do
`$ mv ... ...`
`$ git add -A`
which usually seems to pick up the move, though if git has its own mv thats probably best

**Pull request merged**
