### PR TITLE
Add Elma reading an object oriented programming book

### PR DESCRIPTION
**Pull request by VoidNakamura**
S1EP12 Elma from Dragon Maid is reading an object oriented programming book.

image
image

### CODE REVIEW

**Comment by hdk5** [comment]
You could use a better release

0x539  Miss Kobayashi's Dragon Maid - S01E12 (BD 1080p x264 Hi10P FLAC)  F71ECE7E mkv_002128 764

0x539  Miss Kobayashi's Dragon Maid - S01E12 (BD 1080p x264 Hi10P FLAC)  F71ECE7E mkv_002127 426

**Comment by cat-milk** [comment]
If you could rebase this to be based on master I'll merge it

**Comment by cat-milk** [comment]
Also plus one on the slightly cleaner English version if you're up to the task

**Comment by wheremyfoodat** [comment]
This is a very important PR and it not being merged interferes heavily with my workflow. Can we get a review on it?

**Comment by cat-milk** [comment]
> This is a very important PR and it not being merged interferes heavily with my workflow. Can we get an update and rebase on it?

No because merging it would merge the gh pages branch with the web viewer code in it  into the main branch

**Comment by cat-milk** [comment]
CANNED COPY PASTE REPLY:
This PR has been open for a while and has had requested changes that haven't been addressed. I'm going to close this PR if I don't at least hear back in the next month or two

**Pull request closed without merging**
