### PR TITLE
A few more NodeJs books

### PR DESCRIPTION
**Pull request by Sergiy3013**

### CODE REVIEW

**Review by moonbamijam — CHANGES_REQUESTED** [review]
Please follow the file naming format [here](https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/blob/master/README.md)

For example, (Character name) with (Book name)

**Comment by Sergiy3013** [comment]
The website where the images of the girls were taken did not list their names. 
I've added the book cover and named the files as per your Contribution Guidelines, so I think it's ok if the character names are unknown (it could just be random art)

src:
1) https://wallhaven.cc/w/q6z3xd
2) https://wallhaven.cc/w/r29l8j
3) https://wallhaven.cc/w/42e98x

**Comment by moonbamijam** [comment]
> The website where the images of the girls were taken did not list their names. I've added the book cover and named the files as per your Contribution Guidelines, so I think it's ok if the character names are unknown (it could just be random art)
> 
> src:
> 
> 1. https://wallhaven.cc/w/q6z3xd
> 2. https://wallhaven.cc/w/r29l8j
> 3. https://wallhaven.cc/w/42e98x

since there's no name mentioned, you can try describing what the girl looks like (eg. girl with glasses holding "book", black haired girl with scarf hugging "book")

**Comment by Sergiy3013** [comment]
Ok, I changed the names, hope it's better now
1) Light_Haired_Girl_With_Sword_Holding_Beginning_NodeJs_Book.png
2) Girl_With_Glasses_Blue_Eyes_Covering_Face_With_Express_In_Action_Book.png
3) Black_Haired_Girl_With_Scarf_Holding_NodeJs_Design_Patterns_Book.png

**Comment by cat-milk** [comment]
Looks good, thanks

**Pull request merged**
