### PR TITLE
add: renge holding vuejs book

### PR DESCRIPTION
**Pull request by all123all**
I wasn't sure if it would be good to create a folder for VueJS since there is no folder for React neither, but there is a folder for NodeJS (that actually isn't a language) so i thought that would be fine to create a folder for VueJS.
Also, i have some more images for React and Vue, but i wasn't sure if it would be OK so i'm just sending one picture.

### CODE REVIEW

**Comment by all123all** [comment]
@empty-quiver any update on this?

**Comment by cat-milk** [comment]
I know its been a while since you made this PR but if you could move this image to the JS folder that would be best.

Also the Node.JS folder should probably just not exist.

**Review by cat-milk — CHANGES_REQUESTED** [review]
see my other reply

**Review by cat-milk — APPROVED** [review]

**Comment by cat-milk** [comment]
You know what actually splitting folders by topic is actually ok even if it leads to more a ton more folders eventually. 

If I ask you to keep Vue in the JS folder then why not move the Angular folder too?
If I'm moving angular what about TypeScript? Typescript technically JS but it feels different enough that I think it deserves its own folder. If that's the case though should stuff relating to JSX get its own folder too??? Probably but at that point just make it React folder to avoid confusion. And like if React gets its own folder then Vue should probably get its own too.

Anyways I'm rambling. Merged

**Pull request merged**
