### PR TITLE
added anime girl holding c++ 20 book, let's keep it modern in here 😀

### PR DESCRIPTION
**Pull request by DeaSTL**

### CODE REVIEW

**Comment by Seth-Buchanan** [comment]
This is huge

**Comment by DeaSTL** [comment]
@Seth-Buchanan That's

> This is huge

That's what she said.

**Comment by cat-milk** [comment]
Is this an AI generated anime girl?

**Comment by DeaSTL** [comment]
> Is this an AI generated anime girl?

Yes

**Comment by cat-milk** [comment]
that explains why she looks like that

**Pull request closed without merging**
