### PR TITLE
Add Reimi Sugimoto Clean Code

### PR DESCRIPTION
**Pull request by Vsev0l0d**
Jojo's Reimi Sugimoto with "Clean Code: A Handbook of Agile Software Craftsmanship (Robert C. Martin) (Robert C. Martin Series)"

### CODE REVIEW

**Comment by laynH** [comment]
something about this image feels off. I think its the perspective on the book

**Comment by kotx** [comment]
> something about this image feels off. I think its the perspective on the book

yeah, the left hand is in front of the book which is weird

**Review by cat-milk — CHANGES_REQUESTED** [review]
This image needs a little bit of perspective work to make it look right but I'd be happy to merge it once thats done.

**Comment by cat-milk** [comment]
@Vsev0l0d 

CANNED COPY PASTE REPLY:
This PR has been open for a while and has had requested changes that haven't been addressed. I'm going to close this PR if I don't at least hear back in the next month or two

**Comment by Supercolbat** [comment]
Hello, this PR appeared on my front page, so I figured I might have a go at it. Here's my suggested edit. Evidently, the original image isn't holding a book, so it will look slightly off.

The hash of this uploaded image and my local copy are the same, so no weird compression stuff.

<details><summary>Expand image</summary>

</details>

**Comment by akirataguchi115** [comment]
This PR appeared on my feed as well. Supercolbat's version looks good to me! :heart:

**Pull request closed without merging**
