### PR TITLE
2 cute anime girls for your heart ☺

### PR DESCRIPTION
**Pull request by GermanAizek**
why are you locked in the bathroom son

image

### CODE REVIEW

**Comment by cat-milk** [comment]
I like the image and want to merge this but I feel like I've seen this girl before but I have no idea what her name is. If no one can figure it out then I'll merge it as is.

**Comment by FloatingBanana** [comment]
Her name is Rina Tennoji, from Love Live Nijigasaki

**Comment by kotx** [comment]
cat milk

**Comment by GermanAizek** [comment]
@cat-milk

**Comment by GermanAizek** [comment]
@cat-milk 
added new image (jahy-sama wa kujikenai)

FCKT1f8WYAcLSlw

**Comment by cat-milk** [comment]
@GermanAizek if you update the file names on this PR to match the naming scheme in the ReadMe and also include the names of the girls ill merge it

**Comment by GermanAizek** [comment]
> if you update the file names on this PR to match the naming scheme in the ReadMe and also include the names of the girls ill merge it

ok bro

**Review by greenfodor — CHANGES_REQUESTED** [review]
rename file to match the pattern of the other files
    - FCKT1f8WYAcLSlw.jpg

rename this file as it has a typo, the `H` in `THe` should be lowercase
    - Girl_From_Random_Art_Holds_THe_Art_Of_Computer_Programming.png

**Comment by RDKRACZ** [comment]
Labels can be removed as files were renamed.

**Review by GermanAizek — COMMENTED** [review]
@RDKRACZ I cannot delete PR labels

**Comment by RDKRACZ** [comment]
Yeah, I was talking to the @cat-milk.

**Comment by Kholodets** [comment]
? i mean ill remove them sure but why need them, i merged it a bit ago

**Pull request merged**
