### PR TITLE
Added Rebecca holding Elixir and Erlang books

### PR DESCRIPTION
**Pull request by gboncoffee**
Rebecca is truly the best girl from Edgerunners UwU

### CODE REVIEW

**Comment by cat-milk** [comment]
Sorry for not looking at this sooner but would you mind making a new dir for the erlang image? Erlang is its own language and probably deserves a dedicated directory for its images because of that.

**Review by cat-milk — CHANGES_REQUESTED** [review]
see above comment

**Comment by gboncoffee** [comment]
I'll do!

**Review by Yakaita — COMMENTED** [review]
LGTM

**Comment by gboncoffee** [comment]
Idk if I should have opened another PR but I just added another pic ;)

**Review by cat-milk — APPROVED** [review]

**Pull request merged**
