### PR TITLE
windows, intel, amd

### PR DESCRIPTION
**Pull request by ankushKun**
Added waifus for windows 10, intel and amd to Uncategorised

### CODE REVIEW

**Review by trackpadpro — CHANGES_REQUESTED** [review]
Should be in personification, not uncategorized.

**Comment by ankushKun** [comment]
Moved

**Comment by camblomquist** [comment]
The Intel one isn't a personification, that's Cirno from the Touhou series.

**Comment by tryauuum** [comment]
windows is considered cringe

**Pull request closed without merging**
