### PR TITLE
feat: adding nestjs folder with akeno img

### PR DESCRIPTION
**Pull request by silasoli**
Adding nestjs framework folder together with an image of akeno himejima reading the book
practical nestjs.

### CODE REVIEW

**Comment by cat-milk** [comment]
Even though we have specific directories for stuff like Angular or Vue I think NestJS is similar enough to node that this should just go into the NodeJS folder.

Also sorry about taking so long to review this

**Review by cat-milk — CHANGES_REQUESTED** [review]
move from `NestJs/` to `NodeJs/`

**Comment by silasoli** [comment]
> Even though we have specific directories for stuff like Angular or Vue I think NestJS is similar enough to node that this should just go into the NodeJS folder.
> 
> Also sorry about taking so long to review this

Hello how are you? I hope well.

Requested changes made successfully, sorry I didn't do this before, I wanted a highlighted folder for my favorite framework hehe.

Sorry for the delay.

**Comment by silasoli** [comment]
> move from `NestJs/` to `NodeJs/`

Done

**Pull request merged**
