### PR TITLE
fixed small errors in names

### PR DESCRIPTION
**Pull request by Yakaita**

### CODE REVIEW

**Review by gnubufferoverflows — APPROVED** [review]
LGTM

**Comment by Yakaita** [comment]
what does LGTM mean @gnubufferoverflows

**Comment by GeorgeRNG** [comment]
@Yakaita it's short for "**L**ooks **G**ood **T**o **M**e"

**Comment by cat-milk** [comment]
the casing on some of these still isn't quite right but i get why you wouldn't change that. either way thanks for taking care of the it

**Pull request merged**
