### PR TITLE
adding rebeca from cyberpunk edgerunners holding javascript the definitive guide 

### PR DESCRIPTION
**Pull request by ViniciusTheCoder**
rebs is my favorite character from the anime and i think that this image is very nice :D

### CODE REVIEW

**Comment by gboncoffee** [comment]
OMG REBECCA 🥰

**Review by cat-milk — APPROVED** [review]
Hey could you change the casing on the file name to match the one outlined in the readme?

**Comment by ViniciusTheCoder** [comment]
Done, i renamed to 'Rebeca_Sunrise_JavascriptTheDefinitiveGuide', is it right?

**Comment by cat-milk** [comment]
Perfect thanks

**Pull request merged**
