### PR TITLE
WE WANT FORTH AND WE'LL FIGHT FOR IT(added FORTH directory and random anime girl from quick image search on DDG holding a FORTH book)

### PR DESCRIPTION
**Pull request by segfaultdev**
FORTH has been ignored for ages, marginalized every single time, forgotten and sometimes not even recognized as a programming language. This has to stop. We need to fight this. We, the people, deserve FORTH to be remembered as not only a really good stack based programming language, but as THE BEST LANGUAGE EVER. Big revolutions start with small actions, and it's time for me, segfaultdev, to honor Chuck Moore and add this anime photo I've made in 3 minutes with GIMP and one of the first image results when searching "anime girl holding book" that actually comes from a tutorial on drawing anime glasses, if I remember correctly. Now, I hope you understand our reasoning behind this, and embrace this significant movement with us by merging this pull request as soon as possible. Thanks, and long live FORTH.

### CODE REVIEW

**Comment by SuperLeaf1995** [comment]
we need forth - fuck c, fuck c++l - forth is the only valid lang

**Comment by Ashwin-Paudel** [comment]
+1

**Review by Caslus — APPROVED** [review]

**Comment by asheeeshh** [comment]
what about the girl's name?

**Review by flyingcakes85 — APPROVED** [review]

**Comment by asheeeshh** [comment]
I think she's shiori asagiri from tamako market, not sure 🤔

**Comment by Asday** [comment]
[Like half a minute of investigation](https://www.pixiv.net/en/artworks/64246725), 'snot hard my dudes.

Is "random" the correct designation for original nameless characters?

**Comment by segfaultdev** [comment]
> [Like half a minute of investigation](https://www.pixiv.net/en/artworks/64246725), 'snot hard my dudes.

Well, honestly I didn't even care about the image, just wanted to add FORTH to the repository in some way.

> Is "random" the correct designation for original nameless characters?

Maybe calling it random was a bad idea, though keep in mind that the most important part of the filename(and the only part people will check) is the word "FORTH", as FORTH is the best language ever and no one can say otherwise. Still, to satisfy all the beings that haven't embraced FORTH yet, I'll rename it if necessary. So, what should I name it instead?

**Comment by Asday** [comment]
You're much less amusing than you think you are, but I'm glad you're having fun.

**Comment by segfaultdev** [comment]
> You're much less amusing than you think you are, but I'm glad you're having fun.

I wanted to contribute and be a tad funny in my PR, but I get why it wouldn't be funny for some(or even most) people, so I'm sorry if that annoyed you. Still, ignoring the comments I've made, this is a legit PR trying to add a new language to the repo.

**Comment by Asday** [comment]
Indeed, and I pass no judgement on that - I looked up the art and it turned out there is no need to name the character, as they're nameless, and then wistfully mused whether "random" is an acceptable denomination.  It works for me but I have no clue if it obeys the rules.  I wish you luck with the merge.

**Comment by Kholodets** [comment]
random is acceptable, actually finding the names and either putting that in before uploading or submitting a PR with a fix is encouraged

**Comment by 173duprot** [comment]
+1

**Pull request merged**
