### PR TITLE
add frieren holding c++ book

### PR DESCRIPTION
**Pull request by Chu-4hun**

### CODE REVIEW

**Comment by Chu-4hun** [comment]
Sousou no Frieren_c++

**Review by cat-milk — CHANGES_REQUESTED** [review]
The image here is good but could you replace the spaces in the file name with underscores?

**Comment by Chu-4hun** [comment]
Updated the name of the file to Sousou_no_Frieren_c++

**Comment by cat-milk** [comment]
I think you forgot to add the file create part of the rename to your last commit @Chu-4hun

**Comment by Chu-4hun** [comment]
> I think you forgot to add the file create part of the rename to your last commit @Chu-4hun

I fixed it

**Pull request merged**
