### PR TITLE
feat: add web

### PR DESCRIPTION
**Pull request by beiyuouo**
Now you can see all the girls in the [preview page](https://www.bj-yan.top/Anime-Girls-Holding-Programming-Books/)!

### CODE REVIEW

**Comment by raikasdev** [comment]
> For this repo, you need to enable GitHub Pages when you accept this pull request, as shown in the figure below.
> 
> QQ截图20220302173256

Who the fuck uses GitHub light mode?

**Comment by beiyuouo** [comment]
Maybe it can be achieved in this way. I added figure captions to build the search index. The effect is shown in the figure.
But I don't know how to locate the picture specifically.

preview: [https://www.bj-yan.top/Anime-Girls-Holding-Programming-Books/](https://www.bj-yan.top/Anime-Girls-Holding-Programming-Books/)

QQ截图20220303012328

**Comment by cat-milk** [comment]
I'm sorry but I think I'm going to have to reject this PR. 

While its pretty comfy in terms of being able to easily generate a simple index site for all the image in the repo, I think relying on what is mostly just a markdown/documentation site generator will make adding features like tagging or better image previews a bit more of a pain than I'd like. 

I really appreciate that you took the time to set this up, sorry for the trouble.

**Comment by cat-milk** [comment]
I'm going to close the PR for now but if any other maintainers want to weigh in that might change.

**Comment by DWaffles** [comment]
> I'm going to close the PR for now but if any other maintainers want to weigh in that might change.

Not a maintainer, but an automatically generated front end would be neat *while* a longer term/more robust site is created? 

Although I've seen a few such sites already set up, such as [this one](https://anime-girls-holding-programming-books.netlify.app/) by @Xetera, and the preview page for this one is still up. So it's not like there's a lack of interim sites, they'll just have to be updated by their respective maintainers.

**Comment by Xetera** [comment]
Oh man I made that site a long time ago... I could make it auto-update from this main repo without bothering the current maintainers with PRs if that's a compromise people would be interested in, though I'm not sure if I'm going to have time for it any time soon.

**Pull request closed without merging**
