### PR TITLE
Add Ami holding Purescript by Example

### PR DESCRIPTION
**Pull request by FredTheDino**
Even small programming languages need to have anime girls holding their books.

### CODE REVIEW

**Review by drathier — APPROVED** [review]

**Comment by trackpadpro** [comment]
man why did you not camel case the folder and file title correctly

**Review by TheZoq2 — APPROVED** [review]
LGTM

**Review by rilysh — CHANGES_REQUESTED** [review]
Make each first character a big hand, and use an underscore instead hyphen.

So it'd be, `Ami_Mizuno_Holding_PureScript_By_Example.png`

**Comment by FredTheDino** [comment]
> Make each first character a big hand, and use an underscore instead hyphen.
> 
> So it'd be, `Ami_Mizuno_Holding_PureScript_By_Example.png`

Renamed it to `Ami_Mizuno_Holding_Purescript_By_Example.png`, since they don't capitalize the `s` in the language name.

**Comment by trackpadpro** [comment]
You are still capitalizing PureScript wrong in both the folder and filename.

**Review by Caslus — APPROVED** [review]
i don't see a problem with the file name, it being PureScript or Purescript shouldn't really matter

**Comment by trackpadpro** [comment]
I mean nothing really matters, but on any GitHub repo with the language listed, the book cover in the image on this PR, and pretty much everything, the 's' is capitalized. I have no idea what you are looking at that has it lowercase. Even your own repo capitalizes the 's.'

**Review by rilysh — APPROVED** [review]
looks good!

**Comment by empty-quiver** [comment]
Approved, merging it.

**Pull request merged**
