### PR TITLE
Add Mei Aihara holding Haskell In Depth

### PR DESCRIPTION
**Pull request by JustSlavic**
I made Mei Aihara from Citrus holding Haskell In Depth.
Captions say "This... I found this among your belongings..."

### CODE REVIEW

**Comment by Asday** [comment]
I think that's better translated as "Did this come from your belongings?"  Or simply "Is this yours?"

**Comment by JustSlavic** [comment]
Since there's no か at the end, it's definitely not a question. But phrasing might differ, for sure. Manga translation says "This. This was among the stuff on your desk."
I mentioned translation just in case if someone have questions.

**Comment by hdk5** [comment]
Lack of か doesn't mean that it is not a question, as の can also be a question particle, although more feminine/casual one.
It is still not a question though - の in this case is an explanatory particle.

**Comment by hdk5** [comment]
Additionally, if it is you who made this, you may also add back and side covers, if you want to.

**Comment by JustSlavic** [comment]
Good suggestion. Thanks for pics.

**Comment by hdk5** [comment]
Almost perfect - except for fingernail that is clipping through the side cover.

**Comment by JustSlavic** [comment]
Yeah, my bad, fixed.

**Pull request merged**
