### PR TITLE
Add some TypeMoon waifus in rust lang

### PR DESCRIPTION
**Pull request by sinkaroid**

### CODE REVIEW

**Comment by sinkaroid** [comment]
@cat-milk another wholesome materials ready for review

**Review by cat-milk — CHANGES_REQUESTED** [review]
This looks good but could you please remove the [Rust/Helena_blavatsky_Rust_lang_foundation.png](https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/pull/524/commits/90b94e33760ba17e9389e0a82c42e3ff33fc75ba#diff-c76ab97078111de77682346fa77094ac174cac610a8da9ba4e2c5ee7cb3365fd) and its associated commit? 

Its already kind of much for this repo in terms of how suggestive it is but the way the character looks really doesn't make me comfortable merging this PR as is

**Comment by sinkaroid** [comment]
I completely understand about the policy, but didn't expect that file counted as nsfw too, then what do you think related [e7a6796](https://github.com/cat-milk/Anime-Girls-Holding-Programming-Books/commit/e7a679680243260cf25e9306c032834cfb5fca06) is this also counted?

**Comment by cat-milk** [comment]
@sinkaroid i think that other image is fine tbh. The main problem with this one is that its just on the border of whats acceptable like that other image but the characters perceived age makes me uncomfortable with merging it

**Pull request merged**
